# Use Node 18 as base image
FROM node:18

RUN apt-get update && apt-get install -y python3 make python3-dev libmongocrypt-dev


ENV PYTHON=python3

# Set the working directory in the container
WORKDIR /rethinkpack

# Copy package.json and package-lock.json before other files
COPY package.json .
COPY package-lock.json .

# Install Node.js dependencies
RUN npm install 
# Copy all files to the working directory (except those excluded by .dockerignore)
COPY . .

# Build the application
# RUN npm run build

# Use nginx as base image for the second build stage
# FROM nginx:alpine

# Copy the build output to replace the default nginx contents.
# COPY --from=0 /rethinkpack/build /usr/share/nginx/html

# Expose port 80 for nginx
EXPOSE 3000
EXPOSE 5000
# Start nginx
CMD ["npm","start"]
