FROM node:18
# Install Python using apk
RUN apt-get update && apt-get install -y python3 make python3-dev libmongocrypt-dev

# Set PYTHON environment variable
ENV PYTHON=python3


# Set the working directory
WORKDIR /rethinkpack

# Copy package.json and package-lock.json
COPY package.json .
COPY package-lock.json .

# Install Node.js dependencies

RUN npm install 



# Copy the rest of the application files
COPY . .

# Expose port 5000
EXPOSE 3000
EXPOSE 5000

# Define the command to run the application
CMD ["npm", "start"]


